### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BeauTheBeau**

### CODE REVIEW

**Comment by BeauTheBeau** [comment]
please

**Comment by 19pauer** [comment]
WHAT DO YOU MEAN MY CODE IS GOOD

**Comment by 19pauer** [comment]
BAD HUMAN GO BACK TO PYTHON.

**Comment by BeauTheBeau** [comment]
# nerd

**Comment by 19pauer** [comment]
GO BACK TO THE BAD PYTHON YOU CAME FROM.

**Comment by BeauTheBeau** [comment]
i hope you are forced to use lua

**Pull request closed without merging**
